---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      
  - package-ecosystem: "docker"
    directory: "/php/8.0"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/php/8.1"
    schedule:
      interval: "daily"
